# Generated by Django 6.0.5 on 2026-05-06 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('carpa_dimensiones', models.CharField(blank=True, max_length=80)),
                ('sustrato', models.CharField(blank=True, max_length=120)),
                ('lampara_watts_reales', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lampara_modelo', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('vegetativo', 'Vegetativo'), ('floracion', 'Floración'), ('secado', 'Secado'), ('curado', 'Curado'), ('finalizado', 'Finalizado')], default='vegetativo', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('archivado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Nutriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('npk', models.CharField(blank=True, help_text='Ej: 25-2.8-6.9', max_length=30)),
                ('etapa_recomendada', models.CharField(choices=[('veg', 'Vegetativo'), ('flora', 'Floración'), ('aditivo', 'Aditivo')], default='veg', max_length=10)),
                ('dosis_recomendada_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dosis_recomendada_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Nutriente',
                'verbose_name_plural': 'Nutrientes',
                'ordering': ['marca', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParametroIdeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('vegetativo', 'Vegetativo'), ('floracion', 'Floración'), ('secado', 'Secado')], max_length=20, unique=True)),
                ('temp_min', models.DecimalField(decimal_places=1, max_digits=5)),
                ('temp_max', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hr_min', models.DecimalField(decimal_places=1, max_digits=5)),
                ('hr_max', models.DecimalField(decimal_places=1, max_digits=5)),
                ('ph_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ph_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ec_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ec_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vpd_min', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vpd_max', models.DecimalField(decimal_places=2, max_digits=4)),
                ('horas_luz', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distancia_luz_min', models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True)),
                ('distancia_luz_max', models.PositiveSmallIntegerField(blank=True, help_text='cm', null=True)),
            ],
            options={
                'verbose_name': 'Parámetro ideal',
                'verbose_name_plural': 'Parámetros ideales',
            },
        ),
        migrations.CreateModel(
            name='MedicionAmbiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperatura_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_relativa', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notas', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='growlog.cultivo')),
            ],
            options={
                'verbose_name': 'Medición de ambiente',
                'verbose_name_plural': 'Mediciones de ambiente',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=60)),
                ('strain', models.CharField(blank=True, max_length=120)),
                ('posicion_tent', models.CharField(choices=[('centro', 'Centro'), ('arriba_izq', 'Arriba izquierda'), ('arriba_der', 'Arriba derecha'), ('abajo_izq', 'Abajo izquierda'), ('abajo_der', 'Abajo derecha'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('dias_flora_estimados', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('indica_sativa_ratio', models.CharField(blank=True, help_text='Ej: 70/30', max_length=20)),
                ('thc_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('yield_estimado_g', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('descartada', 'Descartada'), ('cosechada', 'Cosechada')], default='activa', max_length=20)),
                ('notas_genetica', models.TextField(blank=True)),
                ('archivado', models.BooleanField(default=False)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='growlog.cultivo')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['apodo'],
            },
        ),
        migrations.CreateModel(
            name='MedicionPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('nudos_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ancho_canopy_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('aspecto_general', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo')], default='bueno', max_length=10)),
                ('sintomas', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='plantas/%Y/%m/')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='growlog.planta')),
            ],
            options={
                'verbose_name': 'Medición de planta',
                'verbose_name_plural': 'Mediciones de plantas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('topping', 'Topping'), ('lst', 'LST'), ('defoliacion', 'Defoliación'), ('transplante', 'Transplante'), ('problema', 'Problema'), ('diagnostico', 'Diagnóstico'), ('ajuste_ambiente', 'Ajuste de ambiente'), ('cambio_ciclo', 'Cambio de ciclo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('follow_up_fecha', models.DateField(blank=True, null=True)),
                ('follow_up_descripcion', models.TextField(blank=True)),
                ('follow_up_resuelto', models.BooleanField(default=False)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='growlog.cultivo')),
                ('plantas_afectadas', models.ManyToManyField(blank=True, related_name='eventos', to='growlog.planta')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('volumen_total_ml', models.PositiveIntegerField()),
                ('volumen_por_planta_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('ph_agua', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ec_solucion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('buscar_runoff', models.BooleanField(default=False)),
                ('runoff_observado', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to='growlog.cultivo')),
            ],
            options={
                'verbose_name': 'Riego',
                'verbose_name_plural': 'Riegos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NutrienteAplicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis_g_por_litro', models.DecimalField(decimal_places=3, max_digits=6)),
                ('nutriente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='growlog.nutriente')),
                ('riego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrientes_aplicados', to='growlog.riego')),
            ],
            options={
                'verbose_name': 'Nutriente aplicado',
                'verbose_name_plural': 'Nutrientes aplicados',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_objetivo', models.DateField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('urgente', 'Urgente'), ('normal', 'Normal'), ('baja', 'Baja')], default='normal', max_length=10)),
                ('categoria', models.CharField(choices=[('riego', 'Riego'), ('training', 'Training'), ('mantenimiento', 'Mantenimiento'), ('compra', 'Compra'), ('observacion', 'Observación')], default='observacion', max_length=20)),
                ('completada', models.BooleanField(default=False)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='growlog.cultivo')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['completada', 'fecha_objetivo', '-prioridad'],
            },
        ),
    ]
