# Generated by Django 6.0.5 on 2026-05-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0004_set_alan_como_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
    ]
