# Generated by Django 6.0.5 on 2026-05-14 20:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0009_cultivo_dias_estimados'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('entrada', 'Agua de entrada'), ('solucion', 'Solución nutritiva'), ('runoff', 'Runoff / Drenaje'), ('sustrato', 'Sustrato directo')], default='solucion', max_length=20)),
                ('ph', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH')),
                ('ec', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='EC (mS/cm)')),
                ('temp_agua', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temp. agua (°C)')),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Medición EC/pH',
                'verbose_name_plural': 'Mediciones EC/pH',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cambiofotoperiodo',
            name='unique_cultivo_fecha_inicio',
        ),
        migrations.AddField(
            model_name='riego',
            name='ec_runoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='EC runoff (mS/cm)'),
        ),
        migrations.AddField(
            model_name='riego',
            name='ph_runoff',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH runoff'),
        ),
        migrations.AlterField(
            model_name='cambiofotoperiodo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='cambiofotoperiodo',
            unique_together={('cultivo', 'fecha_inicio')},
        ),
        migrations.AddField(
            model_name='medicionec',
            name='cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_ec', to='growlog.cultivo'),
        ),
    ]
