# Generated by Django 6.0.5 on 2026-05-18 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0010_medicionec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanopySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('scrog_fill_pct', models.PositiveSmallIntegerField(default=0)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canopy_snapshots', to='growlog.cultivo')),
            ],
            options={
                'verbose_name': 'Canopy Snapshot',
                'verbose_name_plural': 'Canopy Snapshots',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ColaPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveSmallIntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_cola', to='growlog.planta')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colas', to='growlog.canopysnapshot')),
            ],
            options={
                'verbose_name': 'Posición de Cola',
                'verbose_name_plural': 'Posiciones de Colas',
                'ordering': ['planta', 'indice'],
                'unique_together': {('snapshot', 'planta', 'indice')},
            },
        ),
    ]
