# Generated by Django 6.0.5 on 2026-05-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0011_canopy_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='canopysnapshot',
            name='scrog_cells',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
