# Generated by Django 6.0.5 on 2026-06-10 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0012_add_scrog_cells'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionec',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_ec_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planta',
            name='yield_real_g',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Peso seco final cosechado de esta planta.', null=True, verbose_name='Yield real (g)'),
        ),
    ]
