# Generated by Django 6.0.5 on 2026-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0013_medicionec_creado_por_planta_yield_real_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='fecha_inicio_flora',
            field=models.DateField(blank=True, help_text='Fecha en que se marcó el cambio a floración (flip a ≤12h de luz).', null=True, verbose_name='Fecha de inicio de floración'),
        ),
    ]
