# Generated by Django 6.0.5 on 2026-06-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0015_backfill_fecha_inicio_flora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('watts', models.DecimalField(decimal_places=2, max_digits=8)),
                ('horas_dia', models.DecimalField(decimal_places=2, max_digits=4)),
                ('categoria', models.CharField(choices=[('lampara', 'Lámpara'), ('extractor', 'Extractor'), ('ventilador', 'Ventilador'), ('humidificador', 'Humidificador'), ('otro', 'Otro')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TarifaElectrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('precio_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('distribuidora', models.CharField(default='Edesur', max_length=100)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tarifa eléctrica',
                'verbose_name_plural': 'Tarifas eléctricas',
                'ordering': ['-fecha_desde'],
            },
        ),
        migrations.CreateModel(
            name='LecturaMedidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kwh_real', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_medidor', to='growlog.cultivo')),
            ],
            options={
                'verbose_name': 'Lectura de medidor',
                'verbose_name_plural': 'Lecturas de medidor',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CostoEnergetico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos_energeticos', to='growlog.cultivo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='growlog.equipo')),
                ('tarifa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos', to='growlog.tarifaelectrica')),
            ],
            options={
                'verbose_name': 'Costo energético',
                'verbose_name_plural': 'Costos energéticos',
                'ordering': ['-fecha_desde'],
            },
        ),
    ]
