# Generated by Django 6.0.5 on 2026-07-13 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0016_equipo_tarifaelectrica_lecturamedidor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiegoPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_ml', models.PositiveIntegerField(verbose_name='Volumen (ml)')),
                ('runoff_observado', models.BooleanField(default=False)),
                ('ph_runoff', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='pH runoff')),
                ('ec_runoff', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='EC runoff (mS/cm)')),
                ('notas', models.TextField(blank=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riegos_detalle', to='growlog.planta')),
                ('riego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_plantas', to='growlog.riego')),
            ],
            options={
                'verbose_name': 'Detalle de riego por planta',
                'verbose_name_plural': 'Detalles de riego por planta',
                'ordering': ['planta__apodo'],
                'unique_together': {('riego', 'planta')},
            },
        ),
    ]
