# Generated by Django 6.0.5 on 2026-08-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0019_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='estado',
            field=models.CharField(choices=[('plantula', 'Plántula'), ('vegetativo', 'Vegetativo'), ('floracion', 'Floración'), ('secado', 'Secado'), ('curado', 'Curado'), ('finalizado', 'Finalizado')], default='vegetativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='parametroideal',
            name='etapa',
            field=models.CharField(choices=[('plantula', 'Plántula'), ('vegetativo', 'Vegetativo'), ('floracion', 'Floración'), ('secado', 'Secado')], max_length=20, unique=True),
        ),
    ]
