# Generated by Django 6.0.5 on 2026-08-24 13:25
from django.db import migrations


def crear_parametro_plantula(apps, schema_editor):
    ParametroIdeal = apps.get_model("growlog", "ParametroIdeal")
    ParametroIdeal.objects.get_or_create(
        etapa="plantula",
        defaults=dict(
            temp_min=22, temp_max=26,
            hr_min=65, hr_max=75,
            ph_min="6.0", ph_max="6.8",
            ec_min="0.4", ec_max="0.8",
            vpd_min="0.40", vpd_max="0.80",
            horas_luz=18,
            distancia_luz_min=50, distancia_luz_max=70,
        ),
    )


def borrar_parametro_plantula(apps, schema_editor):
    ParametroIdeal = apps.get_model("growlog", "ParametroIdeal")
    ParametroIdeal.objects.filter(etapa="plantula").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0020_alter_cultivo_estado_alter_parametroideal_etapa'),
    ]

    operations = [
        migrations.RunPython(crear_parametro_plantula, borrar_parametro_plantula),
    ]
