# Generated by Django 6.0.5 on 2026-08-24 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0021_seed_parametro_ideal_plantula'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='tipo',
            field=models.CharField(choices=[('foto', 'Fotoperiódica'), ('auto', 'Autofloreciente')], default='foto', max_length=10),
        ),
        migrations.AlterField(
            model_name='parametroideal',
            name='etapa',
            field=models.CharField(choices=[('plantula', 'Plántula'), ('veg_temprano', 'Veg. temprano'), ('veg_tardio', 'Veg. tardío'), ('flora_temprana', 'Flora temprana'), ('flora_tardia', 'Flora tardía'), ('secado', 'Secado'), ('curado', 'Curado')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='CambioEtapaPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('plantula', 'Plántula'), ('veg_temprano', 'Veg. temprano'), ('veg_tardio', 'Veg. tardío'), ('flora_temprana', 'Flora temprana'), ('flora_tardia', 'Flora tardía'), ('secado', 'Secado'), ('curado', 'Curado')], max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual la planta está en esta etapa', verbose_name='Fecha de inicio')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_etapa', to='growlog.planta')),
            ],
            options={
                'verbose_name': 'Cambio de etapa',
                'verbose_name_plural': 'Cambios de etapa',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('planta', 'fecha_inicio')},
            },
        ),
    ]
