# Generated by Django 6.0.5 on 2026-08-24 15:02
from django.db import migrations

NUEVAS = [
    dict(etapa="veg_temprano", temp_min=22, temp_max=28, hr_min=55, hr_max=70,
         ph_min="6.0", ph_max="6.8", ec_min="0.8", ec_max="1.1",
         vpd_min="0.80", vpd_max="1.00", horas_luz=18, distancia_luz_min=40, distancia_luz_max=60),
    dict(etapa="veg_tardio", temp_min=21, temp_max=27, hr_min=50, hr_max=65,
         ph_min="6.0", ph_max="6.8", ec_min="1.0", ec_max="1.4",
         vpd_min="1.00", vpd_max="1.20", horas_luz=18, distancia_luz_min=35, distancia_luz_max=55),
    dict(etapa="flora_temprana", temp_min=21, temp_max=26, hr_min=45, hr_max=55,
         ph_min="6.0", ph_max="6.8", ec_min="1.2", ec_max="1.7",
         vpd_min="1.00", vpd_max="1.30", horas_luz=12, distancia_luz_min=35, distancia_luz_max=50),
    dict(etapa="flora_tardia", temp_min=20, temp_max=25, hr_min=40, hr_max=50,
         ph_min="6.0", ph_max="6.8", ec_min="1.4", ec_max="2.0",
         vpd_min="1.20", vpd_max="1.50", horas_luz=12, distancia_luz_min=30, distancia_luz_max=45),
]

VIEJAS = [
    dict(etapa="vegetativo", temp_min=22, temp_max=28, hr_min=50, hr_max=70,
         ph_min="6.0", ph_max="6.8", ec_min="0.8", ec_max="1.4",
         vpd_min="0.80", vpd_max="0.95", horas_luz=18, distancia_luz_min=40, distancia_luz_max=60),
    dict(etapa="floracion", temp_min=20, temp_max=26, hr_min=40, hr_max=55,
         ph_min="6.0", ph_max="6.8", ec_min="1.2", ec_max="2.0",
         vpd_min="0.96", vpd_max="1.15", horas_luz=12, distancia_luz_min=35, distancia_luz_max=50),
]


def dividir(apps, schema_editor):
    ParametroIdeal = apps.get_model("growlog", "ParametroIdeal")
    ParametroIdeal.objects.filter(etapa__in=["vegetativo", "floracion"]).delete()
    for datos in NUEVAS:
        ParametroIdeal.objects.get_or_create(etapa=datos["etapa"], defaults=datos)


def revertir(apps, schema_editor):
    ParametroIdeal = apps.get_model("growlog", "ParametroIdeal")
    ParametroIdeal.objects.filter(
        etapa__in=["veg_temprano", "veg_tardio", "flora_temprana", "flora_tardia"]
    ).delete()
    for datos in VIEJAS:
        ParametroIdeal.objects.get_or_create(etapa=datos["etapa"], defaults=datos)


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0022_planta_tipo_alter_parametroideal_etapa_and_more'),
    ]

    operations = [
        migrations.RunPython(dividir, revertir),
    ]
