# Generated by Django 6.0.5 on 2026-10-05 19:38

import django.db.models.deletion
from django.db import migrations, models


ORDEN = ["plantula", "veg_temprano", "veg_tardio", "flora_temprana", "flora_tardia", "secado", "curado"]


def copiar_etapas(apps, schema_editor):
    """Cada cultivo hereda su historial de las etapas de sus plantas (la más
    avanzada de cada fecha, que es lo que ya regía el VPD). Sin historial pero con
    fecha de flora marcada, esa fecha pasa a ser su primera etapa de flora."""
    Cultivo = apps.get_model("growlog", "Cultivo")
    Cambio = apps.get_model("growlog", "CambioEtapaCultivo")
    CambioPlanta = apps.get_model("growlog", "CambioEtapaPlanta")
    for cultivo in Cultivo.objects.all():
        por_fecha = {}
        for c in CambioPlanta.objects.filter(planta__cultivo=cultivo):
            actual = por_fecha.get(c.fecha_inicio)
            if actual is None or ORDEN.index(c.etapa) > ORDEN.index(actual):
                por_fecha[c.fecha_inicio] = c.etapa
        flora = [f for f, e in por_fecha.items() if e.startswith("flora")]
        if cultivo.fecha_inicio_flora and not (flora and min(flora) <= cultivo.fecha_inicio_flora):
            por_fecha[cultivo.fecha_inicio_flora] = "flora_temprana"
        for fecha, etapa in por_fecha.items():
            Cambio.objects.create(cultivo=cultivo, fecha_inicio=fecha, etapa=etapa)
        flora = [f for f, e in por_fecha.items() if e.startswith("flora")]
        if flora:
            cultivo.fecha_inicio_flora = min(flora)
            cultivo.save(update_fields=["fecha_inicio_flora"])


class Migration(migrations.Migration):

    dependencies = [
        ('growlog', '0028_tabla_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='fecha_inicio_flora',
            field=models.DateField(blank=True, editable=False, help_text='Se calcula sola: fecha de la primera etapa de flora del cultivo. Se cambia desde la etapa del cultivo, no a mano.', null=True, verbose_name='Fecha de inicio de floración'),
        ),
        migrations.CreateModel(
            name='CambioEtapaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('plantula', 'Plántula'), ('veg_temprano', 'Veg. temprano'), ('veg_tardio', 'Veg. tardío'), ('flora_temprana', 'Flora temprana'), ('flora_tardia', 'Flora tardía'), ('secado', 'Secado'), ('curado', 'Curado')], max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha desde la cual el cultivo está en esta etapa', verbose_name='Fecha de inicio')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_etapa', to='growlog.cultivo')),
            ],
            options={
                'verbose_name': 'Cambio de etapa del cultivo',
                'verbose_name_plural': 'Cambios de etapa del cultivo',
                'ordering': ['-fecha_inicio', '-pk'],
                'unique_together': {('cultivo', 'fecha_inicio')},
            },
        ),
        migrations.RunPython(copiar_etapas, migrations.RunPython.noop),
    ]
